// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1xu9A16nBoGuK8X3LIbLEoHstntMB94',
    appId: '1:662176364515:web:c8beea2f01e6d2052c12d6',
    messagingSenderId: '662176364515',
    projectId: 'wellbeing-app-d5a53',
    authDomain: 'wellbeing-app-d5a53.firebaseapp.com',
    storageBucket: 'wellbeing-app-d5a53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6IPJsxq0m6JSEfkXXru_SS-G-tQBitA',
    appId: '1:662176364515:android:2765eb4c169a9bc42c12d6',
    messagingSenderId: '662176364515',
    projectId: 'wellbeing-app-d5a53',
    storageBucket: 'wellbeing-app-d5a53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHljo5XkWgLkGNw9Dscn90m1bHrwKgfY',
    appId: '1:662176364515:ios:cf92ddca92f53fdd2c12d6',
    messagingSenderId: '662176364515',
    projectId: 'wellbeing-app-d5a53',
    storageBucket: 'wellbeing-app-d5a53.appspot.com',
    iosClientId: '662176364515-ocqgnq7vuvitgj43rhe8v01g8de426k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiFolder',
  );

}